
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Menu from "./components/menu/Menu";




const myFont = Space_Grotesk({ 
  subsets: ["latin"],
  weight: "400",
  variable: "--font-space-grotesk",
  display: "swap",
});



export const metadata = {
  title: "LUXIMA | Portfolio",
  description: "Generated by Luxima",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={myFont.variable} suppressHydrationWarning={true}>
          
          <Menu />
          {children}
      </body>
    </html>
  );
}
